name: cicd

on:
  push:
    paths: 
      - src/**
    branches: 
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +777 /usr/local/bin/argocd
          mv argocd-linux-amd64 /usr/local/bin/argocd
      
        name: Shorten commit id
        shell: bash
        run:
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: bradcreech617/python-app:${{ env.COMMIT_ID }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      -
        name: Argocd app sync
        shell: bash
        run:
          argocd login http://argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app
